### ISSUE TITLE
ES 1.4+

### ISSUE THREAD

**Issue by popovae** [triforkams/geohash-facet#13]
Hello everyone!

Anybody tried if this plugin still works on ES 1.4+ ?

**Comment by ginaluca** [comment]
Hi,
thanks for the heads up! I'm not working a lot with ES recently, so I guess I let the plugin lag behind... 
It looks like they haven't removed the facet API yet, so at most some minor bug fixing should be needed.

**Comment by popovae** [comment]
Is there any possibility that sometime you will be able to upgrade it? Maybe I can buy you beer or something like this))) Just need it a little bit now for my job((

**Comment by ginaluca** [comment]
I'll try to spend some time on it today.

**Comment by popovae** [comment]
Thank you very-very much! Will appreciate your help!!!

**Comment by popovae** [comment]
I see some updates...is it final or just in work?)

**Comment by ginaluca** [comment]
Hi, the plugin should run fine with ES 1.4.1 now. 

If you want to try it immediately, though, you'll need to build the plugin jar yourself and install it manually. I must have made a mistake when trying to make the release and the versioning is not right: now I need to do some cleanup and create again release 0.018 (ES 1.3) and 0.019 (ES 1.4). My git inexperience is cause of surprises sometimes :)

**Comment by popovae** [comment]
Great, Thank you very much! I will give it a try during weekends)

**Comment by ginaluca** [comment]
Releases should be OK as well now. Have fun!
