### ISSUE TITLE
Version 0.0.9 is not compatible with ES 0.90.7

### ISSUE THREAD

**Issue by timbunce** [triforkams/geohash-facet#2]
I get this error when trying to use version 0.0.9 with ES 0.90.7:

> NoSuchMethodError[org.elasticsearch.index.fielddata.GeoPointValues.getIter(I)Lorg/elasticsearch/index/fielddata/GeoPointValues$Iter;]; 

_I'm using the pre-built .jar in the 0.0.9 release - thanks for that!_

I presume something like this [patch for the geocluster-facet](https://github.com/zenobase/geocluster-facet/commit/0dc40eeb9b375641182972ef2ec25e3a5a146b68) is what's needed. It looks simple so I tried applying it by hand, making the appropriate changes. Sadly I got an error that was beyond my (almost-zero) Java skills, otherwise I'd offer a pull request.

**Comment by ginaluca** [comment]
Upgraded to ES 0.90.6 and 0.90.7. Thanks for making the fix that easy!

**Comment by timbunce** [comment]
And many thanks to you for actually fixing and releasing it! :)
