### ISSUE TITLE
Please always return the bounding box, even when there's only one match within it

### ISSUE THREAD

**Issue by timbunce** [triforkams/geohash-facet#4]
Currently the `top_left` and `bottom_right` are not returned for clusters where `total` is 1. 

This creates a problem if the user wants to show the specific area for each cluster by drawing a box on the map.

**Comment by timbunce** [comment]
Perhaps add a parameter to control the presence of bounding box data in the results.
It could be a value like be 'all', 'none', or 'multi'.

Alternatively, the new param could specify a count of the minimum total to trigger inclusion of bounding box data:
The default would be 2, to match current behaviour.
A value of 1 would give 'all' behaviour.
A very high value would effectively give 'none'.
(Perhaps a 0 could mean return the relevant geohash bounding boxes even if they are empty.)

**Comment by ginaluca** [comment]
The bounding box of a cluster is intended as the minimum rectangle which encloses all the documents contained in the cluster. Therefore the bounding box of a cluster containing 1 document would be a zero-size rectangle, where all the vertices has the same coordinates as the document.

I guess what you want to receive is the area described by the geohash associated to the cluster.

**Comment by timbunce** [comment]
Yes, thanks. I'm waiting on our UI guys to render the data so I've not seen it yet. In my mind I was thinking of a visualization like [this real-estate search map](http://www.bestlosangeleshomesearch.com/results-map/?status=A&swlat=33.819925556778706&swlng=-118.75328065429687&nelat=34.49833242117759&nelng=-117.21931458984375&midlat=34.159810326467145&midlng=-117.98629762207031&zoom=10&firstcall=true&proptype=SF) so I'd been assuming adjacent bounding boxes.

Having the bounding boxes be the actual geohash boundaries, and thus adjacent/touching as in the example above, gives slightly less information to the viewer, but is a lot less visually cluttered than (I imagine) the 'reduced' bounding boxes would be.

An option to return the geohash boundaries instead of the reduced/fitted minimum boundaries would be appreciated.
