### ISSUE TITLE
Changing the factor parameter

### ISSUE THREAD

**Issue by popovae** [triforkams/geohash-facet#7]
Hello.
Is there anyway to change the step of factor parameter. As an example 0.454 as more accurate data is needed...
Thank you for help!

**Comment by ginaluca** [comment]
Hi,

the current algorithm relies on the geohash provided by elasticsearch, which is a 12-char string. This translates in only 13 available steps of clustering. To have smaller steps the plugin should implement the geohash of its own, using a more precise encoding. 

It's on my TODO list since a while, I need to find time to work on it.

**Comment by popovae** [comment]
Hi,

Thank you for reply. So you are saying that this plugin is build on "geohash grid". I ask because the original one (https://github.com/zenobase/geocluster-facet) was build without using it and parameter could be changed to any number...
So you are planing to make this ability someday in future?

PS Sorry for maybe stupid questions as I'm not an IT-specialist and new to ES, just trying to figure out can ES be the good decision for us.

**Comment by ginaluca** [comment]
Yes, this fork of the original project is based geohash calculations, with all the pro and cons. I'm having a look at the code, to see if I can obtain more precision with some easy changes.

**Comment by popovae** [comment]
That will be grate, you would helped me a lot...if it is not really hard for you, please do look at the code..

**Comment by popovae** [comment]
Thank you very much!!! One more small question if you dont mind - in issues you have a commite that adds IDs of record if there is only one in cluster. Dont you know how to implement it? In commit i see the files needed to be changed but I dont understand where to find them on server... Or maybe all the files in the main brunch must be edited and compiled to JAR for setup to server? Can you please explain it in just a few words(

**Comment by ginaluca** [comment]
The feature (show_doc_id flag) is now on trunk, and it's included in the latest release.
