### ISSUE TITLE
The way of clustering

### ISSUE THREAD

**Issue by k3vin-zz** [triforkams/geohash-facet#8]
Hi,

first of all - thanks a lot for such a great plug-in. I'm wondering if it's possible to control how the cluster markers are placed on a map. I am using your demo and it works fine, however markers are always placed in a grid not in a random way - in other words they are so much organized. If you look here: http://www.bikemap.net/ markers are of different sizes and sometimes they overlap. 

![markers](https://f.cloud.github.com/assets/4796591/2515943/88420206-b448-11e3-934d-7863a0931360.jpeg)

Is there a way how to do that or am I just nuts? :) 

Thanks a lot and cheers!

**Comment by ginaluca** [comment]
Hi,

if you see that pattern, then probably your points are evenly spread on the territory. Are they meaningful or did you just generate them to make a test?

In such a situation, the position of each cluster falls very close to the center of the corresponding cell (the position of a cluster is the average of the position of the contained points). Hence, that grid pattern.

You can see something similar in http://www.bikemap.net/ if you zoom out to see the entire Europe, although the pattern is less evident. 

I think If you want to cluster points using a cell based algorithm like the plugin does, you have to accept this visual artefact.

  Gianluca

**Comment by k3vin-zz** [comment]
Dear Gianluca,

thanks a lot for your answer!

Yes, points were generated just for a test. Maybe in a production it would be less evident and hence better :) You're also right with http://www.bikemap.net/ grid-pattern.

And no problem, I'm satisfied with the plug-in, so I accept that ;-)

Cheers,
Jakub
